(async () => {
  const $ = (selector) => document.querySelector(selector);
  const checks = [];
  const check = (name, condition) => { if (!condition) throw new Error(name); checks.push(name); };
  const settle = () => new Promise((resolve) => setTimeout(resolve, 80));
  const visiblePhotos = () => [...document.querySelectorAll('[data-owned-photo]')].filter((button) => !button.closest('figure').hidden);
  check('Signature runtime loaded', typeof window.__protoChecks === 'function');
  $('.menu-toggle').click();
  check('menu opens', $('.menu-toggle').getAttribute('aria-expanded') === 'true');
  $('#main-nav a').click();
  check('menu closes on navigation', $('.menu-toggle').getAttribute('aria-expanded') === 'false');
  $('[data-filter="styling"]').click(); check('styling filter', visiblePhotos().length === 2);
  $('[data-filter="venues"]').click(); check('venue filter', visiblePhotos().length === 1);
  visiblePhotos()[0].click();
  check('lightbox opens', $('[data-photo-dialog]').open);
  await $('.large-photo').decode();
  check('lightbox photograph loads', $('.large-photo').naturalWidth > 0);
  check('single photograph disables navigation', $('.photo-next').disabled && $('.photo-prev').disabled);
  $('[data-close-photo]').click(); await settle();
  check('lightbox focus returns', document.activeElement === visiblePhotos()[0]);
  $('[data-filter="all"]').click(); visiblePhotos()[0].click();
  $('.photo-prev').click(); check('previous wraps to last', $('[data-photo-count]').textContent === '3 / 3');
  $('[data-photo-dialog]').dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  check('keyboard navigation wraps', $('[data-photo-count]').textContent === '1 / 3');
  $('[data-close-photo]').click(); await settle();
  $('.faq-list summary').click(); check('FAQ expands', $('.faq-list details').open);
  $('.faq-list summary').click(); check('FAQ collapses', !$('.faq-list details').open);
  const form = $('#enquiry-form');
  form.reset(); $('[data-service]').click();
  check('service prepopulates enquiry', form.elements.message.value.includes('Concept planning'));
  form.elements.message.value = 'Keep my wording'; document.querySelectorAll('[data-service]')[1].click();
  check('existing enquiry is preserved', form.elements.message.value === 'Keep my wording');
  form.requestSubmit(); check('empty enquiry rejected', !$('#enquiry-dialog').open);
  form.elements.name.value = 'Prototype QA'; form.elements.email.value = 'invalid';
  form.requestSubmit(); check('invalid email rejected', !$('#enquiry-dialog').open);
  form.elements.email.value = 'qa@example.com'; form.elements.message.value = '<b>Literal enquiry text</b>';
  form.requestSubmit(); check('valid enquiry opens summary', $('#enquiry-dialog').open);
  check('enquiry safely rendered', $('[data-enquiry-summary]').textContent.includes('<b>Literal enquiry text</b>') && !$('[data-enquiry-summary] b'));
  check('demo has no send actions', !$('[data-enquiry-email], [data-enquiry-whatsapp]'));
  $('[data-close-enquiry]').click(); await settle();
  check('enquiry edits retained', form.elements.name.value === 'Prototype QA');
  check('scroll lock released', !document.body.classList.contains('dialog-open'));
  form.reset();
  const layout = window.__protoChecks();
  check('no overflow', !layout.overflow);
  check('working links and images', !layout.brokenAnchors.length && !layout.brokenImages.length);
  check('one main heading', document.querySelectorAll('h1').length === 1);
  check('no external runtime requests', performance.getEntriesByType('resource').every((resource) => resource.name.startsWith(location.origin + '/')));
  return { passed: checks.length, checks, layout };
})();
